export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function CartLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<section className="flex w-full max-w-2xl flex-1  flex-col gap-10 py-10  sm:px-6 lg:max-w-7xl lg:flex-row">
			{children}
		</section>
	);
}
