import "./globals.css";
import { type Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/react";
import { Header } from "@/ui/organisms/Header/Header";
import { Footer } from "@/ui/organisms/Footer/Footer";
import { ABreadCrumbs } from "@/ui/atoms/ABreadCrumbs/ABreadCrumbs";

const inter = Inter({ subsets: ["latin"], variable: "--font-gilroy" });

export const metadata: Metadata = {
	title: "Julia's Store",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${inter.variable} flex min-h-screen flex-col bg-white font-sans`}
				>
					<Header />
					<ABreadCrumbs
						homeElement={"Home"}
						separator={<span> {">"} </span>}
						activeClasses="text-secondary"
						containerClasses="flex lg:px-8 py-4"
						listClasses="mx-2 font-normal hover:text-slate-400"
						capitalizeLinks
					/>
					<main className="flex flex-1 flex-grow flex-col justify-center py-4">
						{children}
						<Footer />
					</main>
					{modal}
				</body>
				<Analytics />
			</html>
		</ClerkProvider>
	);
}
